name: 🐞 Bug
description: Reporte um bug
title: "[BUG] <título>"
labels: ["Bug", "Needs Triage"]
body:

  - type: checkboxes
    attributes:
      label: Já existe um problema relacionado a isso?
      description: Por favor, pesquise para ver se já existe um problema relacionado ao bug que você encontrou.
      options:
      - label: Eu pesquisei nos problemas existentes
        required: true

  - type: markdown
    attributes:
      value: |
        Por favor, preencha as seções abaixo para ajudar todos a identificar e corrigir o problema.

  - type: input
    id: versao
    attributes:
      label: Versao do pacote
      description: Qual a versão do pacote?
      placeholder: "0.0.1, 1.3.0 etc"
    validations:
      required: true

  - type: textarea
    id: descricao_problema
    attributes:
      label: Descrição do Problema
      placeholder: Forneça uma descrição clara e concisa do problema que você está enfrentando.
    validations:
      required: true

  - type: textarea
    id: passos_reproducao
    attributes:
      label: Passos para Reproduzir
      placeholder: |
        1. **Passo 1**: Descreva o primeiro passo.
        2. **Passo 2**: Descreva o segundo passo.
        3. **Passo 3**: Descreva o terceiro passo.
    validations:
      required: true

  - type: textarea
    id: comportamento_observado
    attributes:
      label: Comportamento Observado
      placeholder: Descreva o que realmente aconteceu ao seguir os passos.
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Coloque aqui o logs do erro
      placeholder: |
        <logs>
        Tip: Você pode anexar imagens ou arquivos de log clicando nesta área para destacá-la e, em seguida, arrastando os arquivos para dentro.
      render: python
    validations:
      required: true

  - type: textarea
    id: comportamento_esperado
    attributes:
      label: Comportamento Esperado
      placeholder: Descreva o que deveria acontecer.
    validations:
      required: true

  - type: textarea
    id: captura_tela
    attributes:
      label: Captura de Tela (opcional)
      placeholder: Adicione capturas de tela ou vídeos que ajudem a ilustrar o problema.

  - type: textarea
    id: informacoes_adicionais
    attributes:
      label: Informações Adicionais (opcional)
      placeholder: |
        Exemplo
        - **Sistema Operacional:** (ex: Windows 10, macOS, Ubuntu 20.04)
        - Links?

  - type: textarea
    id: sugestoes_solucao
    attributes:
      label: Sugestões de Solução (opcional)
      placeholder: Se você tiver ideias ou sugestões para resolver o problema, compartilhe-as aqui.

  - type: checkboxes
    id: posso_ajudar
    attributes:
      label: Você pode ajudar? (opcional)
      options:
        - label: Posso ajudar a solucionar este problema!

  - type: markdown
    attributes:
      value: |
        Obrigado por relatar este problema!
